### ISSUE TITLE
irssi-notifier.sh cat issue

### ISSUE THREAD

**Issue by rorymobley** [stickster/irssi-libnotify#28]
when i get a message i'm seeing this in irssi (the notification *does* get shown). debian 8.6 64-bit

14:29 cat: /proc/7752: Is a directory
14:29 cat: 23917/environ: No such file or directory
14:32 cat: /proc/7752: Is a directory
14:32 cat: 23917/environ: No such file or directory

**Comment by bkylerussell** [comment]
#33 should resolve this.
